const stores = [
  {
    id: 1,
    name: 'Store 1',
    streets: 'Street 1',
    storethumbnail: 'https://placehold.co/200x200',
    orderbanner: 'https://placehold.co/700x200',
    storebanner: 'https://placehold.co/700x200',
    favour: 0,
    favouriteId: 0,
  },
  {
    id: 2,
    name: 'Store 2',
    streets: 'Street 2',
    storethumbnail: 'https://placehold.co/200x200',
    orderbanner: 'https://placehold.co/700x200',
    storebanner: 'https://placehold.co/700x200',
    favour: 0,
    favouriteId: 0,
  },
  {
    id: 3,
    name: 'Store 3',
    streets: 'Street 3',
    storethumbnail: 'https://placehold.co/200x200',
    orderbanner: 'https://placehold.co/700x200',
    storebanner: 'https://placehold.co/700x200',
    favour: 0,
    favouriteId: 0,
  },
];
const favourites = [];
const products = [
  {
    id: 1,
    store_id: 1,
    name: 'Product 1',
    price: 100,
    image: 'https://placehold.co/200x200',
    category: 'Category 1',
    description: 'Description Product 1 Store 1 Category 1',
  },
  {
    id: 2,
    store_id: 1,
    name: 'Product 2',
    price: 100,
    image: 'https://placehold.co/200x200',
    category: 'Category 1',
    description: 'Description Product 2 Store 1 Category 1',
  },
  {
    id: 3,
    store_id: 1,
    name: 'Product 3',
    price: 100,
    image: 'https://placehold.co/200x200',
    category: 'Category 2',
    description: 'Description Product 3 Store 1 Category 2',
  },
  {
    id: 4,
    store_id: 1,
    name: 'Product 4',
    price: 100,
    image: 'https://placehold.co/200x200',
    category: 'Category 2',
    description: 'Description Product 4 Store 1 Category 2',
  },
  {
    id: 5,
    store_id: 2,
    name: 'Product 1',
    price: 100,
    image: 'https://placehold.co/200x200',
    category: 'Category 1',
    description: 'Description Product 1 Store 2 Category 1',
  },
  {
    id: 6,
    store_id: 2,
    name: 'Product 2',
    price: 100,
    image: 'https://placehold.co/200x200',
    category: 'Category 1',
    description: 'Description Product 2 Store 2 Category 1',
  },
  {
    id: 7,
    store_id: 2,
    name: 'Product 3',
    price: 100,
    image: 'https://placehold.co/200x200',
    category: 'Category 2',
    description: 'Description Product 3 Store 2 Category 2',
  },
  {
    id: 8,
    store_id: 2,
    name: 'Product 4',
    price: 100,
    image: 'https://placehold.co/200x200',
    category: 'Category 2',
    description: 'Description Product 4 Store 2 Category 2',
  },
  {
    id: 9,
    store_id: 3,
    name: 'Product 1',
    price: 100,
    image: 'https://placehold.co/200x200',
    category: 'Category 1',
    description: 'Description Product 1 Store 3 Category 1',
  },
  {
    id: 10,
    store_id: 3,
    name: 'Product 2',
    price: 100,
    image: 'https://placehold.co/200x200',
    category: 'Category 1',
    description: 'Description Product 2 Store 3 Category 1',
  },
  {
    id: 11,
    store_id: 3,
    name: 'Product 3',
    price: 100,
    image: 'https://placehold.co/200x200',
    category: 'Category 2',
    description: 'Description Product 3 Store 3 Category 2',
  },
  {
    id: 12,
    store_id: 3,
    name: 'Product 4',
    price: 100,
    image: 'https://placehold.co/200x200',
    category: 'Category 2',
    description: 'Description Product 4 Store 3 Category 2',
  },
];
const carts = [];
const orders = [];

module.exports = {
  stores,
  favourites,
  products,
  carts,
  orders,
};
